name: C/C++ CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build project
      run: make -j 4
    - name: Run project
      run: ./build/hello
